<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_FHAAAAAAAH HHH</name>
   <tag></tag>
   <elementGuidId>5f9c178e-9b86-460a-abbc-638fef8dcc0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-userdropdown-name ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.oxd-userdropdown-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d44d0c2d-2c5f-49d0-84c1-cfc7689aa821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-userdropdown-name</value>
      <webElementGuid>48eab3c2-27fa-41d9-8be2-38c85a422fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FHAAAAAAAH HHH</value>
      <webElementGuid>bea059e8-2f97-473d-be26-0fa157f7fb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-776f8cef8ba4c548be8dae8141afa63b</value>
      <webElementGuid>549657a7-9c2c-4d6b-b57b-e1f777d5627b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-userdropdown-name ')]</value>
      <webElementGuid>42d8d056-56ac-40e1-b13c-a21812884caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-userdropdown-name ')]</value>
      <webElementGuid>27ea2d75-f3f4-4c9c-a418-f1e04828da47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'FHAAAAAAAH HHH' or . = 'FHAAAAAAAH HHH')]</value>
      <webElementGuid>d384eea0-0f72-4cdd-9ef7-83aa867e5316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
